/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-tertiary-container": "#003d3b",
              "primary": "#006a64",
              "secondary": "#575e70",
              "on-secondary-fixed-variant": "#404758",
              "tertiary-container": "#55aca9",
              "primary-fixed-dim": "#51dad0",
              "on-secondary": "#ffffff",
              "on-error-container": "#93000a",
              "tertiary-fixed-dim": "#7fd5d2",
              "primary-container": "#00b1a7",
              "on-primary": "#ffffff",
              "outline-variant": "#bbc9c7",
              "surface-container-high": "#e7e8ea",
              "on-background": "#191c1e",
              "surface-dim": "#d9dadc",
              "error": "#ba1a1a",
              "secondary-fixed": "#dce2f7",
              "inverse-on-surface": "#f0f1f3",
              "on-primary-container": "#003d39",
              "on-surface-variant": "#3c4948",
              "surface-tint": "#006a64",
              "inverse-surface": "#2e3132",
              "inverse-primary": "#51dad0",
              "background": "#f8f9fb",
              "on-tertiary-fixed-variant": "#00504e",
              "white": "#FFFFFF",
              "on-surface": "#191c1e",
              "on-tertiary-fixed": "#00201f",
              "on-secondary-container": "#5c6274",
              "on-tertiary": "#ffffff",
              "status-error": "#EF4444",
              "on-secondary-fixed": "#141b2b",
              "surface-container": "#edeef0",
              "outline": "#6c7a78",
              "surface-container-lowest": "#ffffff",
              "surface": "#f8f9fb",
              "tertiary": "#006a68",
              "primary-fixed": "#72f7ec",
              "surface-container-low": "#f3f4f6",
              "secondary-fixed-dim": "#c0c6db",
              "status-listening": "#00B1A7",
              "on-primary-fixed": "#00201e",
              "surface-bright": "#f8f9fb",
              "on-error": "#ffffff",
              "secondary-container": "#d9dff5",
              "surface-variant": "#e1e2e4",
              "on-primary-fixed-variant": "#00504b",
              "status-connecting": "#3B82F6",
              "tertiary-fixed": "#9bf1ee",
              "error-container": "#ffdad6",
              "surface-container-highest": "#e1e2e4",
              "status-speaking": "#8B5CF6"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "gutter": "24px",
              "unit": "8px",
              "touch-target": "56px",
              "margin-mobile": "16px",
              "margin-desktop": "64px"
          },
          "fontFamily": {
              "headline-lg-mobile": ["Montserrat", "sans-serif"],
              "body-md": ["Montserrat", "sans-serif"],
              "body-xl": ["Montserrat", "sans-serif"],
              "headline-lg": ["Montserrat", "sans-serif"],
              "label-lg": ["Montserrat", "sans-serif"],
              "body-lg": ["Montserrat", "sans-serif"],
              "headline-xl-mobile": ["Montserrat", "sans-serif"],
              "headline-xl": ["Montserrat", "sans-serif"],
              "label-sm": ["Montserrat", "sans-serif"]
          },
          "fontSize": {
              "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
              "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "body-xl": ["20px", { "lineHeight": "30px", "fontWeight": "500" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
              "label-lg": ["16px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
              "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
              "headline-xl-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "label-sm": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
          }
      },
  },
  plugins: [],
}
